name: Post-run Cleanup 

on:
  workflow_run:
    workflows: [Continuous Integration, Release]
    types:
      - completed

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Delete Artifacts
        uses: wearefrank/ci-cd-templates/delete-workflow-artifacts@delete-workflow-artifacts
        with:
          token: ${{ github.token }}
          artifact-names: 'report-?, build-*, report-a'
          workflow-run-id: ${{ github.event.workflow_run.id }}