name: Release

on:
  push:
    branches:
      - main
      - master

jobs:
  docusaurus-release:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: wearefrank/ci-cd-templates/.github/workflows/docusaurus-release.yml@docusaurus
